//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reamke.Model
{
    using Reamke.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang : BaseViewModel
    {
        public int IDGioHang { get; set; }
        public Nullable<int> IDSanPham { get; set; }
        public string TenSanPham { get; set; }
        Nullable<int>  _SoLuong;
        public Nullable<int> SoLuong { get => _SoLuong; set { _SoLuong = value; OnPropertyChanged(); } }
        public Nullable<double> DonGia { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
